import type { SqliteDatabase } from "../storage/sqlite.ts";
import { withTransaction } from "../storage/index.ts";
type Input=Record<string,unknown>; type Row=Record<string,unknown>;
export class CommandError extends Error{constructor(message:string,public status=400){super(message)}}
const text=(v:unknown)=>typeof v==="string"?v.trim():"", num=(v:unknown)=>Number(v), id=(p:string)=>`${p}-${crypto.randomUUID()}`;
const positive=(v:unknown,label:string,zero=false)=>{const n=num(v);if(!Number.isFinite(n)||(zero?n<0:n<=0))throw new CommandError(`${label} غير صالح`);return n};
const one=(db:SqliteDatabase,sql:string,...args:unknown[])=>db.prepare(sql).get(...args) as Row|undefined;
const all=(db:SqliteDatabase,sql:string,...args:unknown[])=>db.prepare(sql).all(...args) as Row[];
const docBase=(kind:string,prefix:string)=>({id:id(kind),number:`${prefix}-${Date.now()}-${crypto.randomUUID().slice(0,6)}`,kind,status:"posted",occurredAt:new Date().toISOString()});
function insertDocument(db:SqliteDatabase,d:Row,lines:Row[]=[]){db.prepare(`INSERT INTO documents(id,number,kind,status,party_id,warehouse_id,destination_warehouse_id,parent_document_id,payment_method,title,total,due_total,paid_total,occurred_at,business_date,daily_sequence,recurring_id,occurrence_key,legacy_key,payload) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(d.id,d.number,d.kind,d.status??"posted",d.partyId??null,d.warehouseId??null,d.destinationWarehouseId??null,d.parentDocumentId??null,d.paymentMethod??null,d.title??null,d.total??0,d.dueTotal??0,d.paidTotal??0,d.occurredAt,d.businessDate??null,d.dailySequence??null,d.recurringId??null,d.occurrenceKey??null,d.legacyKey??null,JSON.stringify(d));lines.forEach((l,i)=>db.prepare(`INSERT INTO document_lines(id,document_id,product_id,description,quantity,unit_price,line_total,cost_at_sale,gross_profit,position,payload) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(l.id,d.id,l.productId??null,l.description??"",l.quantity??0,l.unitPrice??0,l.lineTotal??0,l.costAtSale??null,l.grossProfit??null,i,JSON.stringify(l)));}
function account(db:SqliteDatabase,key:unknown){const a=one(db,"SELECT * FROM payment_accounts WHERE (id=? OR code=?) AND is_active=1",text(key),text(key));if(!a)throw new CommandError("يجب اختيار وسيلة دفع صالحة");return a}
function finance(db:SqliteDatabase,d:Row,direction:"in"|"out",amount:number,type:string,allowNegative=false){if(!amount)return;const a=account(db,d.paymentMethod),delta=direction==="in"?amount:-amount;if(direction==="out"&&!allowNegative&&num(a.balance)<amount)throw new CommandError(`الرصيد غير كافٍ في ${a.name}`);db.prepare("UPDATE payment_accounts SET balance=balance+? WHERE id=?").run(delta,a.id);db.prepare(`INSERT INTO financial_movements(id,document_id,document_number,payment_account_id,direction,amount,party_id,type,transfer_id,occurred_at,note,payload) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id("fin"),d.id,d.number??null,a.id,direction,amount,d.partyId??null,type,d.transferId??null,d.occurredAt,d.note??null,JSON.stringify(d));}
function stock(db:SqliteDatabase,p:Row,w:Row,delta:number,d:Row,type:string){const current=one(db,"SELECT quantity FROM product_stocks WHERE product_id=? AND warehouse_id=?",p.id,w.id),before=num(current?.quantity??0),after=before+delta;if(after<0)throw new CommandError(`المخزون غير كافٍ للمنتج ${p.name}`);db.prepare("INSERT INTO product_stocks(product_id,warehouse_id,quantity) VALUES(?,?,?) ON CONFLICT(product_id,warehouse_id) DO UPDATE SET quantity=excluded.quantity").run(p.id,w.id,after);db.prepare(`INSERT INTO stock_movements(id,document_id,document_number,warehouse_id,product_id,type,quantity_delta,balance_before,balance_after,occurred_at,payload) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id("mov"),d.id,d.number,w.id,p.id,type,delta,before,after,d.occurredAt,JSON.stringify({warehouseName:w.name,productName:p.name}));return{before,after}}
function inputLines(body:Input){if(!Array.isArray(body.lines)||!body.lines.length)throw new CommandError("يجب إضافة منتج واحد على الأقل");const seen=new Set();return body.lines.map<Row>(x=>{const r=x as Input,productId=text(r.productId),quantity=positive(r.quantity,"الكمية");if(!productId||seen.has(productId))throw new CommandError("المنتجات غير صالحة أو مكررة");seen.add(productId);return{...r,productId,quantity}})}
function productMap(db:SqliteDatabase,lines:Row[]){const map=new Map<string,Row>();for(const l of lines){const p=one(db,"SELECT * FROM products WHERE id=? AND is_archived=0",l.productId);if(!p)throw new CommandError("أحد المنتجات غير موجود",404);map.set(String(p.id),p)}return map}

export function executeCommand(body:Input){return withTransaction(db=>{const type=text(body.type),now=new Date().toISOString();db.prepare("INSERT INTO audit_events(id,actor_id,action,created_at,details) VALUES(?,?,?,?,?)").run(id("audit"),"local-owner",type,now,"started");let result:string;
 if(type==="party.create"){const name=text(body.name),phone=text(body.phone);if(!name)throw new CommandError("اسم الطرف مطلوب");const old=phone&&one(db,"SELECT id FROM parties WHERE phone=?",phone);if(old)return String(old.id);result=id("party");db.prepare("INSERT INTO parties(id,name,phone,roles,created_at) VALUES(?,?,?,?,?)").run(result,name,phone,JSON.stringify(["customer","supplier"]),now)}
 else if(type==="warehouse.create"){const name=text(body.name);if(!name)throw new CommandError("اسم المخزن مطلوب");result=id("wh");db.prepare("INSERT INTO warehouses(id,name,created_at) VALUES(?,?,?)").run(result,name,now)}
 else if(type==="warehouse.update"){result=text(body.id);if(!text(body.name)||!db.prepare("UPDATE warehouses SET name=? WHERE id=?").run(text(body.name),result).changes)throw new CommandError("المخزن غير موجود",404)}
 else if(type==="warehouse.default"){result=text(body.warehouseId);if(!one(db,"SELECT id FROM warehouses WHERE id=?",result))throw new CommandError("المخزن غير موجود",404);db.prepare("UPDATE warehouses SET is_sales_default=0").run();db.prepare("UPDATE warehouses SET is_sales_default=1 WHERE id=?").run(result)}
 else if(type==="product.create"){const name=text(body.name),barcode=text(body.barcode);if(!name)throw new CommandError("اسم المنتج مطلوب");if(barcode&&one(db,"SELECT id FROM products WHERE barcode=?",barcode))throw new CommandError("هذا الباركود مستخدم لمنتج آخر",409);const opening=body.openingStock==null||body.openingStock===""?0:positive(body.openingStock,"رصيد البداية",true),cost=body.pieceCost==null||body.pieceCost===""?null:positive(body.pieceCost,"سعر الشراء",true);if(opening&&!cost)throw new CommandError("سعر الشراء للفرد مطلوب عند إدخال رصيد بداية");const max=num(one(db,"SELECT max(CAST(sku AS INTEGER)) value FROM products WHERE sku GLOB '[0-9]*'")?.value??0),counter=num(one(db,"SELECT value FROM counters WHERE key='productSequence'")?.value??0)+1,seq=Math.max(max+1,counter);db.prepare("UPDATE counters SET value=?,updated_at=? WHERE key='productSequence'").run(seq,now);result=id("product");db.prepare(`INSERT INTO products(id,sku,barcode,name,piece_cost,piece_price,last_purchase_cost,last_purchase_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(result,String(seq),barcode||null,name,cost,body.piecePrice==null||body.piecePrice===""?null:positive(body.piecePrice,"سعر البيع",true),opening?cost:null,opening?now:null,now);if(opening){const w=one(db,"SELECT * FROM warehouses WHERE is_sales_default=1")??one(db,"SELECT * FROM warehouses WHERE id=?",text(body.openingWarehouseId));if(!w)throw new CommandError("مخزن رصيد البداية مطلوب");const d={...docBase("adjustment","OPEN"),warehouseId:w.id,title:"رصيد بداية"},l={id:id("line"),productId:result,description:name,quantity:opening,unitPrice:cost,lineTotal:0};stock(db,{id:result,name},w,opening,d,"opening");insertDocument(db,d,[l])}}
 else if(type==="product.update"){result=text(body.id);const barcode=text(body.barcode);if(barcode&&one(db,"SELECT id FROM products WHERE barcode=? AND id<>?",barcode,result))throw new CommandError("هذا الباركود مستخدم لمنتج آخر",409);if(!db.prepare("UPDATE products SET name=?,barcode=?,piece_cost=?,piece_price=? WHERE id=?").run(text(body.name),barcode||null,body.pieceCost===""?null:num(body.pieceCost),body.piecePrice===""?null:num(body.piecePrice),result).changes)throw new CommandError("المنتج غير موجود",404)}
 else if(type==="product.delete"){result=text(body.id);const qty=num(one(db,"SELECT sum(quantity) value FROM product_stocks WHERE product_id=?",result)?.value??0);if(qty>0)throw new CommandError("لا يمكن حذف المنتج ولديه مخزون. صفّر المخزون أولًا من تصحيح المخزون.",409);const used=one(db,"SELECT 1 x FROM document_lines WHERE product_id=? LIMIT 1",result);used?db.prepare("UPDATE products SET is_archived=1,archived_at=? WHERE id=?").run(now,result):db.prepare("DELETE FROM products WHERE id=?").run(result)}
 else if(type==="sale.post"||type==="purchase.post"){const sale=type==="sale.post",ls=inputLines(body),ps=productMap(db,ls),w=one(db,"SELECT * FROM warehouses WHERE id=?",text(body.warehouseId));if(!w)throw new CommandError("المخزن غير موجود",404);const party=text(body.partyId)?one(db,"SELECT * FROM parties WHERE id=?",text(body.partyId)):undefined,method=text(body.paymentMethod)||"cash";if(method==="note"&&!party)throw new CommandError("الطرف غير موجود",404);if(method!=="note")account(db,method);const calc=ls.map(l=>{const p=ps.get(String(l.productId))!,price=positive(sale?l.piecePrice:l.unitPrice,sale?"سعر الفرد":"سعر الشراء"),cost=p.last_purchase_cost==null?null:num(p.last_purchase_cost);if(sale&&cost!=null&&price<cost)throw new CommandError(`لا يمكن البيع تحت سعر الشراء. سعر الشراء الحالي: ${cost} MRU`);const total=Math.round(num(l.quantity)*price);return{id:id("line"),productId:l.productId,description:p.name,quantity:l.quantity,unitPrice:price,lineTotal:total,...(sale?{costAtSale:cost,grossProfit:cost==null?null:total-num(l.quantity)*cost}:{})}}),total=calc.reduce((s,l)=>s+num(l.lineTotal),0),paid=method==="note"?0:total,due=total-paid,businessDate=now.slice(0,10),daily=sale?num(one(db,"SELECT max(daily_sequence) value FROM documents WHERE kind='sale' AND business_date=?",businessDate)?.value??0)+1:null,d={...docBase(sale?"sale":"purchase",sale?"SAL":"PUR"),partyId:party?.id??null,warehouseId:w.id,paymentMethod:method,total,dueTotal:due,paidTotal:paid,businessDate,dailySequence:daily};for(const l of ls)stock(db,ps.get(String(l.productId))!,w,sale?-num(l.quantity):num(l.quantity),d,sale?"sale":"purchase");insertDocument(db,d,calc);if(!sale)for(const l of calc)db.prepare("UPDATE products SET last_purchase_cost=?,last_purchase_at=? WHERE id=?").run(l.unitPrice,d.occurredAt,l.productId);if(due&&party)db.prepare(`UPDATE parties SET ${sale?"receivable=receivable+?,net=net+?":"payable=payable+?,net=net-?"} WHERE id=?`).run(due,due,party.id);if(paid)finance(db,d,sale?"in":"out",paid,sale?"sale":"purchase",!sale);result=String(d.id)}
 else if(type==="transfer.post"){const ls=inputLines(body),ps=productMap(db,ls),from=one(db,"SELECT * FROM warehouses WHERE id=?",text(body.fromWarehouseId)),to=one(db,"SELECT * FROM warehouses WHERE id=?",text(body.toWarehouseId));if(!from||!to||from.id===to.id)throw new CommandError("اختر مخزنين مختلفين");const d={...docBase("transfer","TRF"),warehouseId:from.id,destinationWarehouseId:to.id};const dl=ls.map(l=>({id:id("line"),productId:l.productId,description:ps.get(String(l.productId))!.name,quantity:l.quantity,unitPrice:0,lineTotal:0}));for(const l of ls){const p=ps.get(String(l.productId))!;stock(db,p,from,-num(l.quantity),d,"transfer-out");stock(db,p,to,num(l.quantity),d,"transfer-in")}insertDocument(db,d,dl);result=String(d.id)}
 else if(type==="adjustment.post"){const ls=inputLines({...body,lines:(body.lines as Input[]).map(l=>({...l,quantity:1}))}),ps=productMap(db,ls),w=one(db,"SELECT * FROM warehouses WHERE id=?",text(body.warehouseId)),reason=text(body.reason);if(!w)throw new CommandError("المخزن غير موجود",404);if(!reason)throw new CommandError("سبب التصحيح مطلوب");const d={...docBase("adjustment","ADJ"),warehouseId:w.id,title:reason},dl=[];for(const l of ls){const p=ps.get(String(l.productId))!,before=num(one(db,"SELECT quantity FROM product_stocks WHERE product_id=? AND warehouse_id=?",p.id,w.id)?.quantity??0),after=positive(l.actualQuantity,"الرصيد الفعلي",true),cost=l.purchaseCost==null||l.purchaseCost===""?null:positive(l.purchaseCost,"تكلفة الشراء");if(after>before&&p.last_purchase_cost==null&&cost==null)throw new CommandError(`تكلفة الشراء مطلوبة لإضافة مخزون المنتج ${p.name}`);if(cost!=null&&after>before)db.prepare("UPDATE products SET last_purchase_cost=?,last_purchase_at=? WHERE id=?").run(cost,d.occurredAt,p.id);stock(db,p,w,after-before,d,"adjustment");dl.push({id:id("line"),productId:p.id,description:`${p.name} — ${reason} (قبل ${before}، بعد ${after})`,quantity:after-before,unitPrice:cost??p.last_purchase_cost??0,lineTotal:0})}insertDocument(db,d,dl);result=String(d.id)}
 else if(type==="expense.post"){const title=text(body.title),amount=positive(body.amount,"المبلغ"),date=text(body.occurredAt),frequency=text(body.frequency);if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new CommandError("العنوان والتاريخ مطلوبان");if(frequency==="daily"||frequency==="monthly"){result=id("rec");db.prepare("INSERT INTO recurring_expenses(id,title,amount,frequency,starts_on,created_at) VALUES(?,?,?,?,?,?)").run(result,title,amount,frequency,date,now)}else{const d={...docBase("expense","EXP"),occurredAt:new Date(`${date}T12:00:00Z`).toISOString(),paymentMethod:text(body.paymentMethod),title,total:amount,paidTotal:amount};account(db,d.paymentMethod);finance(db,d,"out",amount,"expense");insertDocument(db,d,[{id:id("line"),productId:null,description:title,quantity:1,unitPrice:amount,lineTotal:amount}]);result=String(d.id)}}
 else if(type==="payment-account.create"){if(!text(body.name)||!/^#[0-9a-f]{6}$/i.test(text(body.color)))throw new CommandError("بيانات وسيلة الدفع غير صالحة");result=id("account");db.prepare("INSERT INTO payment_accounts(id,code,name,color,icon,created_at) VALUES(?,?,?,?,?,?)").run(result,id("custom"),text(body.name),text(body.color),"wallet",now)}
 else if(type==="payment-account.update"){result=text(body.id);if(!db.prepare("UPDATE payment_accounts SET name=?,color=?,is_active=? WHERE id=?").run(text(body.name),text(body.color),body.isActive===false?0:1,result).changes)throw new CommandError("وسيلة الدفع غير موجودة",404)}
 else if(type==="account-transfer.post"){const from=account(db,body.fromAccountId),to=account(db,body.toAccountId),amount=positive(body.amount,"المبلغ");if(from.id===to.id)throw new CommandError("اختر حسابين مختلفين");const transferId=id("transfer"),d={...docBase("payment-transfer","BTR"),transferId,paymentMethod:from.id,note:text(body.note)};finance(db,d,"out",amount,"transfer-out");d.paymentMethod=to.id;finance(db,d,"in",amount,"transfer-in");db.prepare("INSERT INTO account_transfers(id,number,from_account_id,to_account_id,amount,note,occurred_at,payload) VALUES(?,?,?,?,?,?,?,?)").run(transferId,d.number,from.id,to.id,amount,d.note,d.occurredAt,JSON.stringify(d));result=transferId}
 else throw new CommandError("العملية غير مدعومة");db.prepare("INSERT INTO audit_events(id,actor_id,action,entity_id,created_at,details) VALUES(?,?,?,?,?,?)").run(id("audit"),"local-owner",type,result,new Date().toISOString(),"committed");return result})}
