import { EJSON } from "bson";
import { copyFileSync,mkdirSync,writeFileSync } from "node:fs";
import { join } from "node:path";
import { getStorage } from "./storage/index.ts";
import { resolveContaPaths } from "./paths.ts";
export const BACKUP_COLLECTIONS=["products","warehouses","parties","documents","stockMovements","recurringExpenses","financialMovements","paymentAccounts","accountTransfers"] as const;
type Backup={format:"conta-backup";schemaVersion:1|2;createdAt:string;appVersion:string;encoding:string;collections:Record<string,Record<string,unknown>[]>;counts:Record<string,number>};
const tables:Record<string,string>={products:"products",warehouses:"warehouses",parties:"parties",documents:"documents",stockMovements:"stock_movements",recurringExpenses:"recurring_expenses",financialMovements:"financial_movements",paymentAccounts:"payment_accounts",accountTransfers:"account_transfers"};
export function createNativeBackup(_legacy?:unknown):Backup{const db=getStorage(),collections=Object.fromEntries(BACKUP_COLLECTIONS.map(k=>[k,db.prepare(`SELECT * FROM ${tables[k]}`).all() as Record<string,unknown>[]])) as Record<string,Record<string,unknown>[]>;return{format:"conta-backup",schemaVersion:2,createdAt:new Date().toISOString(),appVersion:"1.0.0",encoding:"conta-logical-json-v2",collections,counts:Object.fromEntries(BACKUP_COLLECTIONS.map(k=>[k,collections[k].length]))}}
export function stringifyBackup(b:Backup){return JSON.stringify(b)}
export function parseAndValidateBackup(raw:string){const b=(raw.includes('mongodb-extended-json')?EJSON.parse(raw):JSON.parse(raw)) as Backup;if(b?.format!=="conta-backup"||![1,2].includes(b.schemaVersion)||!b.collections)throw new Error("صيغة النسخة الاحتياطية غير صالحة");return b}
export function createSafetyBackup(reason:string){const paths=resolveContaPaths();mkdirSync(paths.backups,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,"-");const path=join(paths.backups,`safety-${reason}-${stamp}.db`);const db=getStorage();db.pragma("wal_checkpoint(FULL)");copyFileSync(paths.database,path);db.prepare("INSERT INTO safety_backups(id,reason,path,created_at) VALUES(?,?,?,?)").run(crypto.randomUUID(),reason,path,new Date().toISOString());return path}
export function writeDailyBackup(){const p=resolveContaPaths();mkdirSync(p.backups,{recursive:true});const path=join(p.backups,`conta-${new Date().toISOString().slice(0,10)}.json`);if(!requireExists(path))writeFileSync(path,stringifyBackup(createNativeBackup()),{flag:"wx"});return path}function requireExists(path:string){try{return !!(globalThis as unknown as {process:unknown}).process&&!!requireStat(path)}catch{return false}}function requireStat(path:string){try{const fs=process.getBuiltinModule?.("fs") as typeof import("node:fs")|undefined;return fs?.existsSync(path)}catch{return false}}
export function restoreNativeBackup(b:Backup){createSafetyBackup("before-restore");const db=getStorage();db.transaction(()=>{for(const k of [...BACKUP_COLLECTIONS].reverse())db.prepare(`DELETE FROM ${tables[k]}`).run();if(b.schemaVersion===2){for(const k of BACKUP_COLLECTIONS){const rows=b.collections[k]??[];for(const row of rows){const keys=Object.keys(row).filter(x=>x!=="_id"),sql=`INSERT INTO ${tables[k]}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`;db.prepare(sql).run(...keys.map(x=>typeof row[x]==="object"?JSON.stringify(row[x]):row[x]))}}}else restoreV1(db,b);})();}
function restoreV1(db:ReturnType<typeof getStorage>,b:Backup){for(const w of b.collections.warehouses??[])db.prepare("INSERT INTO warehouses(id,name,is_sales_default,legacy_key,created_at,payload) VALUES(?,?,?,?,?,?)").run(String(w._id??w.id),w.name,Boolean(w.isSalesDefault)?1:0,w.legacyKey??null,String(w.createdAt??new Date().toISOString()),JSON.stringify(w));for(const p of b.collections.products??[]){db.prepare("INSERT INTO products(id,sku,barcode,name,piece_cost,piece_price,last_purchase_cost,last_purchase_at,is_archived,legacy_key,created_at,payload) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(p.id,p.sku,p.barcode||null,p.name,p.pieceCost??null,p.piecePrice??null,p.lastPurchaseCost??null,p.lastPurchaseAt??null,p.isArchived?1:0,p.legacyKey??null,String(p.createdAt??new Date().toISOString()),JSON.stringify(p));for(const [wid,q] of Object.entries(p.stocks??{}))db.prepare("INSERT INTO product_stocks(product_id,warehouse_id,quantity) VALUES(?,?,?)").run(p.id,wid,q)}for(const a of b.collections.paymentAccounts??[])db.prepare("INSERT INTO payment_accounts(id,code,name,color,icon,is_active,balance,legacy_key,created_at,payload) VALUES(?,?,?,?,?,?,?,?,?,?)").run(a.id,a.code,a.name,a.color??"#64748b",a.icon??"wallet",a.isActive===false?0:1,a.balance??0,a.legacyKey??null,String(a.createdAt??new Date().toISOString()),JSON.stringify(a));for(const p of b.collections.parties??[])db.prepare("INSERT INTO parties(id,name,phone,roles,receivable,payable,net,legacy_key,created_at,payload) VALUES(?,?,?,?,?,?,?,?,?,?)").run(p.id,p.name,p.phone??"",JSON.stringify(p.roles??[]),p.receivable??0,p.payable??0,p.net??0,p.legacyKey??null,String(p.createdAt??new Date().toISOString()),JSON.stringify(p));}

export async function rebuildCounters(_legacy?:unknown){const db=getStorage(),max=Number((db.prepare("SELECT max(CAST(sku AS INTEGER)) value FROM products").get() as {value:number|null}).value??0);db.prepare("UPDATE counters SET value=max(value,?),updated_at=? WHERE key='productSequence'").run(max,new Date().toISOString())}
