import type { ReportFilters, ReportResponse, ReportRow, ReportType } from "../app/report-types.ts";
import { getStorage } from "./storage/index.ts";
const TYPES: ReportType[] = ["overview", "sales", "purchases", "product-sales", "stock", "profit", "debts", "party-ledger", "financial", "expenses", "returns"];
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const text = (value: string | null) => (value ?? "").trim();
const isoDate = (value: string, next = false) => { const date = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(date.valueOf()) || date.toISOString().slice(0, 10) !== value) throw new Error("التاريخ غير صالح"); if (next) date.setUTCDate(date.getUTCDate() + 1); return date; };
export function parseReportFilters(url: URL): ReportFilters {
  const type = text(url.searchParams.get("type")) as ReportType;
  if (!TYPES.includes(type)) throw new Error("نوع التقرير غير صالح");
  const from = text(url.searchParams.get("from")), to = text(url.searchParams.get("to"));
  if (type !== "debts" && (!DATE.test(from) || !DATE.test(to))) throw new Error("الفترة مطلوبة");
  if (from && to && isoDate(from) > isoDate(to)) throw new Error("بداية الفترة يجب ألا تتجاوز نهايتها");
  if (from && to && (isoDate(to).valueOf() - isoDate(from).valueOf()) / 86400000 > 3660) throw new Error("الفترة طويلة جدًا");
  const page = Number(url.searchParams.get("page") ?? 1), pageSize = Number(url.searchParams.get("pageSize") ?? 100);
  if (!Number.isInteger(page) || page < 1 || !Number.isInteger(pageSize) || pageSize < 1 || pageSize > 200) throw new Error("إعدادات الصفحة غير صالحة");
  const pick = <T extends string>(key: string, allowed: T[], fallback?: T) => { const value = text(url.searchParams.get(key)); if (!value) return fallback; if (!allowed.includes(value as T)) throw new Error(`الفلتر ${key} غير صالح`); return value as T; };
  return { type, from: from || undefined, to: to || undefined, partyId: text(url.searchParams.get("partyId")) || undefined, productId: text(url.searchParams.get("productId")) || undefined, paymentAccountId: text(url.searchParams.get("paymentAccountId")) || undefined, movementType: text(url.searchParams.get("movementType")) || undefined, direction: pick("direction", ["in", "out"]), groupBy: pick("groupBy", ["invoice", "product"], "invoice"), sortBy: pick("sortBy", ["quantity", "sales", "name", "profit"], "quantity"), debtSide: pick("debtSide", ["receivable", "payable", "clear"]), expenseType: pick("expenseType", ["once", "recurring"]), search: text(url.searchParams.get("search")) || undefined, page, pageSize };
}

const n=(v:unknown)=>Number(v??0); const page=(rows:ReportRow[],f:ReportFilters)=>rows.slice((f.page-1)*f.pageSize,f.page*f.pageSize);const meta=(total:number,f:ReportFilters)=>({page:f.page,pageSize:f.pageSize,totalRows:total,totalPages:Math.max(1,Math.ceil(total/f.pageSize))});
export function buildReport(f:ReportFilters):ReportResponse{const db=getStorage(),from=`${f.from}T00:00:00.000Z`,to=`${f.to}T23:59:59.999Z`;
 if(f.type==="debts"){let rows=db.prepare("SELECT id partyId,id,name,phone,receivable,payable,receivable-payable net,last_movement_at lastMovement FROM parties ORDER BY name").all() as ReportRow[];if(f.search)rows=rows.filter(x=>String(x.name).includes(f.search!)||String(x.phone).includes(f.search!));if(f.debtSide==="receivable")rows=rows.filter(x=>n(x.receivable)>0);if(f.debtSide==="payable")rows=rows.filter(x=>n(x.payable)>0);if(f.debtSide==="clear")rows=rows.filter(x=>n(x.receivable)<=0&&n(x.payable)<=0);return{report:f.type,from:null,to:null,summary:{receivable:rows.reduce((s,x)=>s+n(x.receivable),0),payable:rows.reduce((s,x)=>s+n(x.payable),0),net:rows.reduce((s,x)=>s+n(x.net),0)},rows:page(rows,f),meta:meta(rows.length,f)}}
 if(f.type==="stock"){let rows=db.prepare(`SELECT sm.id,sm.document_id documentId,sm.occurred_at occurredAt,p.sku,p.name product,w.name warehouse,sm.type movementType,sm.balance_before before,sm.quantity_delta change,sm.balance_after after,sm.document_number documentNumber FROM stock_movements sm JOIN products p ON p.id=sm.product_id JOIN warehouses w ON w.id=sm.warehouse_id WHERE sm.occurred_at BETWEEN ? AND ? ORDER BY sm.occurred_at DESC`).all(from,to) as ReportRow[];if(f.productId)rows=rows.filter(x=>x.productId===f.productId);return{report:f.type,from:f.from!,to:f.to!,summary:{movements:rows.length,incoming:rows.reduce((s,x)=>s+Math.max(0,n(x.change)),0),outgoing:rows.reduce((s,x)=>s+Math.abs(Math.min(0,n(x.change))),0)},rows:page(rows,f),meta:meta(rows.length,f)}}
 if(f.type==="financial"){let rows=db.prepare(`SELECT fm.id,fm.document_id documentId,fm.occurred_at occurredAt,fm.payment_account_id paymentMethod,fm.type movementType,CASE WHEN direction='in' THEN amount ELSE 0 END incoming,CASE WHEN direction='out' THEN amount ELSE 0 END outgoing,fm.document_number documentNumber FROM financial_movements fm WHERE occurred_at BETWEEN ? AND ? ORDER BY occurred_at DESC`).all(from,to) as ReportRow[];const operating=rows.filter(x=>!String(x.movementType).startsWith("transfer-"));return{report:f.type,from:f.from!,to:f.to!,summary:{incoming:rows.reduce((s,x)=>s+n(x.incoming),0),outgoing:rows.reduce((s,x)=>s+n(x.outgoing),0),net:rows.reduce((s,x)=>s+n(x.incoming)-n(x.outgoing),0),operatingIncoming:operating.reduce((s,x)=>s+n(x.incoming),0),operatingOutgoing:operating.reduce((s,x)=>s+n(x.outgoing),0),operatingNet:operating.reduce((s,x)=>s+n(x.incoming)-n(x.outgoing),0)},rows:page(rows,f),meta:meta(rows.length,f)}}
 const kind=f.type==="sales"?"sale":f.type==="purchases"?"purchase":f.type==="expenses"?"expense":f.type==="returns"?"return":null;if(kind){const rows=db.prepare(`SELECT id,id documentId,number,occurred_at occurredAt,title,total,paid_total paid,due_total due,payment_method paymentMethod,parent_document_id parentDocument FROM documents WHERE kind=? AND occurred_at BETWEEN ? AND ? ORDER BY occurred_at DESC`).all(kind,from,to) as ReportRow[];return{report:f.type,from:f.from!,to:f.to!,summary:{count:rows.length,total:rows.reduce((s,x)=>s+n(x.total),0),grossSales:rows.reduce((s,x)=>s+n(x.total),0),netSales:rows.reduce((s,x)=>s+n(x.total),0),paid:rows.reduce((s,x)=>s+n(x.paid),0),due:rows.reduce((s,x)=>s+n(x.due),0)},rows:page(rows,f),meta:meta(rows.length,f)}}
 const daily=db.prepare(`SELECT substr(occurred_at,1,10) date,SUM(CASE WHEN kind='sale' THEN total WHEN kind='return' THEN -total ELSE 0 END) sales,SUM(CASE WHEN kind='purchase' THEN total ELSE 0 END) purchases,SUM(CASE WHEN kind='expense' THEN total ELSE 0 END) expenses FROM documents WHERE occurred_at BETWEEN ? AND ? GROUP BY substr(occurred_at,1,10) ORDER BY date`).all(from,to) as ReportRow[];const summary={sales:daily.reduce((s,x)=>s+n(x.sales),0),purchases:daily.reduce((s,x)=>s+n(x.purchases),0),expenses:daily.reduce((s,x)=>s+n(x.expenses),0),profit:0,unknownRevenue:0};return{report:f.type,from:f.from!,to:f.to!,summary,rows:page(daily,f),meta:meta(daily.length,f)} }
